Parameters:
  S3BucketNameForEventLambdaCode:
    Type: String
    Default: lambda-code-hello-word
    Description: The s3 bucket which contain lambda code
  S3BucketObjectKeyForEventLambdaCode:
    Type: String
    Default: hello-world.zip
    Description: The s3 bucket which contain lambda code
  EventLambdaLogGroupName:
    Type: String
    Default: hello-world-lambda-log-group
    Description: The log group for event lambda

Resources:
  MyEventLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref S3BucketNameForEventLambdaCode
        S3Key: !Ref S3BucketObjectKeyForEventLambdaCode
      Handler: "index.handler"
      Role:  !GetAtt EventLambdaExecutionRole.Arn
      Runtime: "nodejs12.x"
      Timeout: 900
      Environment:
        Variables:
          TABLE_NAME: !Select [1, !Split ['/', !GetAtt MyDynamoDBTable.Arn]]
          REGION: !Ref AWS::Region

  EventLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        - PolicyName: hello-world-lambda-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource:
                  - arn:aws:logs:*:*:log-group:/aws/lambda/*:*
                  - !GetAtt MyDynamoDBTable.Arn

  EventLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: MyEventLambda
    Properties:
      LogGroupName: !Ref EventLambdaLogGroupName
      RetentionInDays: 30

  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "UserId"
          AttributeType: "N"
        -
          AttributeName: "Label"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "UserId"
          KeyType: "HASH"
        -
          AttributeName: "Label"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
