Parameters:
  S3BucketNameForLambdaCode:
    Type: String
    Default: sunjing-week2-lambda-code
    Description: The s3 bucket which contain lambda code
  S3BucketObjectKeyForLambdaCode:
    Type: String
    Default: lambda.zip
    Description: The s3 bucket which contain lambda code

Resources:
  SunJingLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: Ref S3BucketNameForLambdaCode
        S3Key: Ref S3BucketObjectKeyForLambdaCode
      Handler: "index.handler"
      Role:  !GetAtt LambdaExecutionRole.Arn
      Runtime: "nodejs12.x"
      Timeout: 900
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        - PolicyName: hello-world-lambda-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:*:*:log-group:/aws/lambda/*:*
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: MyLambda
    Properties:
      LogGroupName: hello-world-lambda-log-group
      RetentionInDays: 30
